### ISSUE TITLE
Add way to continue when uncommitted changes are found

### ISSUE THREAD

**Issue by byteit101** [postmodern/rubygems-tasks#17]
### User Story/Rant
This line: https://github.com/postmodern/rubygems-tasks/blob/f5def3317720d2004c8ae237190a2efbc425ff0a/lib/rubygems/tasks/scm/status.rb#L34 was so annoying to get around today. I was trying to printf-debug an application, depending on a second (ruby, 3rd party) library, with the `printf`s in a 3rd library (in C, 3rd party). This 3rd library I had to compile via `rake gem` for changes to take effect. But, every time I tried to compile, I got:

```txt
!!! Project has uncommitted changes!
```

sigh...
and so I got in the habit of `git commit -am "junk" ` before every `rake gem` and so far today I have 11 useless commits. Can I prune them? Of course, but the UX on this was **so frustrating**, and to top it all off, that error was ungoogleable! I was hoping for some easy way to disable it, but no, I had to do actual, completely useless commits. I also tried removing the .git directory, which made that check pass, but the rakefile for the C library used git commands, so that didn't work for me.

### Request
For most ruby libraries, the stance of "you must have committed changes" makes sense, and I applaud it, but there are some libraries and situations it doesn't:

 * I'm not the maintainer & building a modified version of the source is easier than the old trick of symlinking from the gems dir (aka libraries with complicated rakefile/generated sources)
 * I'm not the maintainer & building is required (it's not pure ruby, so needs to be compiled)
 * I'm not the maintainer & I'm hacking in debugging aids for a different project (never going to commit or upstream that)

As such, I'd like a way to temporarily disable the aborting of builds without everything checked in. Perhaps something like `rake gem[allow_dirty_repo]` ?

**Comment by nmalaguti** [comment]
You can configure rubygems in your Rakefile to ignore dirty status.

```ruby
require 'rubygems/tasks'

Gem::Tasks.new(scm: {status: false})
```

**Comment by postmodern** [comment]
Closing this since the `scm:status`/`validate` task can be disabled via `Gem::Tasks.new(scm: {status: false})`. If you need to bypass `rubygems-tasks` *completely* you can do `gem build foo.gemspec`. Also, you could have used bundler to bundle the 3rd-party gem with the `path:` option, to avoid having to build and install the gem.
